### ISSUE TITLE
Does this hostapd have rtl8812AU 8821AU support?

### ISSUE THREAD

**Issue by satindergrewal** [igorpecovnik/hostapd#1]
I compiled https://github.com/abperiasamy/rtl8812AU_8821AU_linux on my Raspberry Pi 2.
WiFi is working fine, but Access Point is not working.

Wondering if this hostapd will do the trick?
Is there any recommended/default hostapd.conf for this chip?

Cheers,
Satinder

**Comment by igorpecovnik** [comment]
This hostapd is official plus few patches. It's similar to the openwrt where those patches came from. This adapter should work in 2.4Ghz but I read that on 5 it doesn't or there are problems ... I am not 100% sure but you probably need to use Realtek version (rtl871xdrv) of hostapd. My script creates both from one source. That's the whole point.

**Comment by satindergrewal** [comment]
Thanks compiled hostapd from this repo and using following hostapd.conf

works! :)

# Basic configuration

interface=wlan1
ssid=WiFi_SSID
channel=5

# WPA and WPA2 configuration

macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=Some_PassWord
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP

# Hardware configuration

driver=nl80211
ieee80211ac=1
hw_mode=g

/etc/hostapd/hostapd.conf (END)

**Comment by pnduffy** [comment]
Thanks for this!  Spent hours trying to get hostapd working and found this script.  Fixed my problem!
