### ISSUE TITLE
E: Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by davi-domo** [igorpecovnik/hostapd#4]
hello,

I have an error at the time Downloading dependencies.
>root@orangepipc:~/hostapd# ./go.sh 
[ o.k. ] Building hostapd
[ o.k. ] Downloading dependencies.
E: Unable to correct problems, you have held broken packages.
Outside chroot
[ o.k. ] Updating sources.
[ o.k. ] Compiling v2.5 for Realteks.
[ o.k. ] Compiling v2.5.
[ err. ] hostapd not built.

Here is my distrib

> Armbian_5.26_Orangepipc_Debian_jessie_3.4.113

Realized order

> cd /usr/src/linux-headers-3.4.113-sun8i/
>make scripts
>apt-get update && apt-get upgrade
>git clone https://github.com/igorpecovnik/hostapd
>chmod +x ./hostapd/go.sh
>cd hostapd
>root@orangepipc:~/hostapd# ./go.sh 
[ o.k. ] Building hostapd
[ o.k. ] Downloading dependencies.
E: Unable to correct problems, you have held broken packages.
Outside chroot
[ o.k. ] Updating sources.
[ o.k. ] Compiling v2.5 for Realteks.
[ o.k. ] Compiling v2.5.
[ err. ] hostapd not built.

do you have an idea ?

**Comment by igorpecovnik** [comment]
It looks like previous PR was wrong: https://github.com/igorpecovnik/hostapd/commit/3acfd258bf6809c88c05189908ce8944b46f1cfb

Remove libnl* from apt-get and try again

**Comment by davi-domo** [comment]
ok perfect thanks
